### ISSUE TITLE
np.reddit.com uses browser

### ISSUE THREAD

**Issue by Sec42** [zagaberoo/diode#61] opened 2017-07-10 17:26 UTC
Links to np.reddit.com do not get handled by diode, but go to the browser, which in turn gives the mobile website. These links should be handled by diode internally like normal reddit links

**Comment by zagaberoo** [comment] 2017-07-10 18:30
Links clicked within Diode or other places?  It's supposed to already handle them: https://github.com/zagaberoo/diode/blob/master/AndroidManifest.xml#L51

You must have hit some sort of edge case: can you give me an example to reproduce the issue?

**Comment by Sec42** [comment] 2017-07-23 09:32
it happens for me multiple times a day. Looking at a sample link just now, the main difference I see that my link starts with https:// instead of http://.

**Comment by zagaberoo** [comment] 2017-07-25 16:51
Aha; that's the key.  Looks like Diode doesn't support HTTPS links at all, even beyond np.reddit.com links.  Fortunately it should be a super easy fix.

Thanks for reporting!

**Comment by zagaberoo** [comment] 2017-07-26 03:10
Should be fixed in the next release:

https://github.com/zagaberoo/diode/commit/646d67f0791c6cda21c4815967fcc6e1f695db4a

**Closed by zagaberoo** 2017-07-26 03:10 UTC

**Comment by Sec42** [comment] 2017-07-26 22:40
Thanks. Will test it once it's released :)
